# Generated by Django 5.2.6 on 2025-10-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_venta_cliente_remove_venta_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
